pref<-c(8,4,5,3)
pie(pref,col=rainbow(4),main="Movie type preferences",,clockwise=TRUE,labels=pref)
legend("topright",c("comedy","action","romance","science or fiction") ,fill=rainbow(4))               
barplot(pref,xlab="movietype",ylab="no of persons",names.arg=c("comedy","action","romance","science or fiction"))
m<-matrix(data=sample(50:100,12),3,4)
m
barplot(m,names.arg =c("1-3","3-6","6-9","9-12"))
d<-mtcars$mpg
hist(d,ylab="type",xlab="milepergallon")
plot.new()
abline(h=0,v=0)
x<-c(20,5,4,8,16)
t<-c(15,18,2,14,3)
points(x,y)
plot(x,y)
lines(x,y)
abline(h=max(t))
dev.off()
abline(v=max(x))
drugA <-c(16, 20, 27, 40, 60)
drugB <-c(15, 18, 25, 31, 40)
dosage<-c(10,20,30,40,50)
plot(drugA,dosage,xlab="drugs",type="o")
lines(drugB,dosage)
airquality
boxplot(airquality$Temp,airquality$Month)
plot(iris$Sepal.Length,iris$Sepal.Width,type="s")
pairs(~Sepal.Length+Sepal.Width,data=iris)